// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ServicesColumns holds the columns for the "Services" table.
	ServicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "created_on", Type: field.TypeTime},
	}
	// ServicesTable holds the schema information for the "Services" table.
	ServicesTable = &schema.Table{
		Name:       "Services",
		Columns:    ServicesColumns,
		PrimaryKey: []*schema.Column{ServicesColumns[0]},
	}
	// ServiceVersionsColumns holds the columns for the "ServiceVersions" table.
	ServiceVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "created_on", Type: field.TypeTime},
		{Name: "service_id", Type: field.TypeInt},
	}
	// ServiceVersionsTable holds the schema information for the "ServiceVersions" table.
	ServiceVersionsTable = &schema.Table{
		Name:       "ServiceVersions",
		Columns:    ServiceVersionsColumns,
		PrimaryKey: []*schema.Column{ServiceVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ServiceVersions_Services_versions",
				Columns:    []*schema.Column{ServiceVersionsColumns[3]},
				RefColumns: []*schema.Column{ServicesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ServicesTable,
		ServiceVersionsTable,
	}
)

func init() {
	ServicesTable.Annotation = &entsql.Annotation{
		Table: "Services",
	}
	ServiceVersionsTable.ForeignKeys[0].RefTable = ServicesTable
	ServiceVersionsTable.Annotation = &entsql.Annotation{
		Table: "ServiceVersions",
	}
}
