// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"services/ent/predicate"
	"services/ent/service"
	"services/ent/serviceversion"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServiceVersionQuery is the builder for querying ServiceVersion entities.
type ServiceVersionQuery struct {
	config
	ctx         *QueryContext
	order       []serviceversion.Order
	inters      []Interceptor
	predicates  []predicate.ServiceVersion
	withService *ServiceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ServiceVersionQuery builder.
func (svq *ServiceVersionQuery) Where(ps ...predicate.ServiceVersion) *ServiceVersionQuery {
	svq.predicates = append(svq.predicates, ps...)
	return svq
}

// Limit the number of records to be returned by this query.
func (svq *ServiceVersionQuery) Limit(limit int) *ServiceVersionQuery {
	svq.ctx.Limit = &limit
	return svq
}

// Offset to start from.
func (svq *ServiceVersionQuery) Offset(offset int) *ServiceVersionQuery {
	svq.ctx.Offset = &offset
	return svq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (svq *ServiceVersionQuery) Unique(unique bool) *ServiceVersionQuery {
	svq.ctx.Unique = &unique
	return svq
}

// Order specifies how the records should be ordered.
func (svq *ServiceVersionQuery) Order(o ...serviceversion.Order) *ServiceVersionQuery {
	svq.order = append(svq.order, o...)
	return svq
}

// QueryService chains the current query on the "service" edge.
func (svq *ServiceVersionQuery) QueryService() *ServiceQuery {
	query := (&ServiceClient{config: svq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := svq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := svq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(serviceversion.Table, serviceversion.FieldID, selector),
			sqlgraph.To(service.Table, service.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, serviceversion.ServiceTable, serviceversion.ServiceColumn),
		)
		fromU = sqlgraph.SetNeighbors(svq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ServiceVersion entity from the query.
// Returns a *NotFoundError when no ServiceVersion was found.
func (svq *ServiceVersionQuery) First(ctx context.Context) (*ServiceVersion, error) {
	nodes, err := svq.Limit(1).All(setContextOp(ctx, svq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{serviceversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (svq *ServiceVersionQuery) FirstX(ctx context.Context) *ServiceVersion {
	node, err := svq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ServiceVersion ID from the query.
// Returns a *NotFoundError when no ServiceVersion ID was found.
func (svq *ServiceVersionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = svq.Limit(1).IDs(setContextOp(ctx, svq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{serviceversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (svq *ServiceVersionQuery) FirstIDX(ctx context.Context) int {
	id, err := svq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ServiceVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ServiceVersion entity is found.
// Returns a *NotFoundError when no ServiceVersion entities are found.
func (svq *ServiceVersionQuery) Only(ctx context.Context) (*ServiceVersion, error) {
	nodes, err := svq.Limit(2).All(setContextOp(ctx, svq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{serviceversion.Label}
	default:
		return nil, &NotSingularError{serviceversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (svq *ServiceVersionQuery) OnlyX(ctx context.Context) *ServiceVersion {
	node, err := svq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ServiceVersion ID in the query.
// Returns a *NotSingularError when more than one ServiceVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (svq *ServiceVersionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = svq.Limit(2).IDs(setContextOp(ctx, svq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{serviceversion.Label}
	default:
		err = &NotSingularError{serviceversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (svq *ServiceVersionQuery) OnlyIDX(ctx context.Context) int {
	id, err := svq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ServiceVersions.
func (svq *ServiceVersionQuery) All(ctx context.Context) ([]*ServiceVersion, error) {
	ctx = setContextOp(ctx, svq.ctx, "All")
	if err := svq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ServiceVersion, *ServiceVersionQuery]()
	return withInterceptors[[]*ServiceVersion](ctx, svq, qr, svq.inters)
}

// AllX is like All, but panics if an error occurs.
func (svq *ServiceVersionQuery) AllX(ctx context.Context) []*ServiceVersion {
	nodes, err := svq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ServiceVersion IDs.
func (svq *ServiceVersionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if svq.ctx.Unique == nil && svq.path != nil {
		svq.Unique(true)
	}
	ctx = setContextOp(ctx, svq.ctx, "IDs")
	if err = svq.Select(serviceversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (svq *ServiceVersionQuery) IDsX(ctx context.Context) []int {
	ids, err := svq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (svq *ServiceVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, svq.ctx, "Count")
	if err := svq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, svq, querierCount[*ServiceVersionQuery](), svq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (svq *ServiceVersionQuery) CountX(ctx context.Context) int {
	count, err := svq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (svq *ServiceVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, svq.ctx, "Exist")
	switch _, err := svq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (svq *ServiceVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := svq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ServiceVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (svq *ServiceVersionQuery) Clone() *ServiceVersionQuery {
	if svq == nil {
		return nil
	}
	return &ServiceVersionQuery{
		config:      svq.config,
		ctx:         svq.ctx.Clone(),
		order:       append([]serviceversion.Order{}, svq.order...),
		inters:      append([]Interceptor{}, svq.inters...),
		predicates:  append([]predicate.ServiceVersion{}, svq.predicates...),
		withService: svq.withService.Clone(),
		// clone intermediate query.
		sql:  svq.sql.Clone(),
		path: svq.path,
	}
}

// WithService tells the query-builder to eager-load the nodes that are connected to
// the "service" edge. The optional arguments are used to configure the query builder of the edge.
func (svq *ServiceVersionQuery) WithService(opts ...func(*ServiceQuery)) *ServiceVersionQuery {
	query := (&ServiceClient{config: svq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	svq.withService = query
	return svq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ServiceVersion.Query().
//		GroupBy(serviceversion.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (svq *ServiceVersionQuery) GroupBy(field string, fields ...string) *ServiceVersionGroupBy {
	svq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ServiceVersionGroupBy{build: svq}
	grbuild.flds = &svq.ctx.Fields
	grbuild.label = serviceversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ServiceVersion.Query().
//		Select(serviceversion.FieldName).
//		Scan(ctx, &v)
func (svq *ServiceVersionQuery) Select(fields ...string) *ServiceVersionSelect {
	svq.ctx.Fields = append(svq.ctx.Fields, fields...)
	sbuild := &ServiceVersionSelect{ServiceVersionQuery: svq}
	sbuild.label = serviceversion.Label
	sbuild.flds, sbuild.scan = &svq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ServiceVersionSelect configured with the given aggregations.
func (svq *ServiceVersionQuery) Aggregate(fns ...AggregateFunc) *ServiceVersionSelect {
	return svq.Select().Aggregate(fns...)
}

func (svq *ServiceVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range svq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, svq); err != nil {
				return err
			}
		}
	}
	for _, f := range svq.ctx.Fields {
		if !serviceversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if svq.path != nil {
		prev, err := svq.path(ctx)
		if err != nil {
			return err
		}
		svq.sql = prev
	}
	return nil
}

func (svq *ServiceVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ServiceVersion, error) {
	var (
		nodes       = []*ServiceVersion{}
		_spec       = svq.querySpec()
		loadedTypes = [1]bool{
			svq.withService != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ServiceVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ServiceVersion{config: svq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, svq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := svq.withService; query != nil {
		if err := svq.loadService(ctx, query, nodes, nil,
			func(n *ServiceVersion, e *Service) { n.Edges.Service = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (svq *ServiceVersionQuery) loadService(ctx context.Context, query *ServiceQuery, nodes []*ServiceVersion, init func(*ServiceVersion), assign func(*ServiceVersion, *Service)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ServiceVersion)
	for i := range nodes {
		fk := nodes[i].ServiceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(service.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "service_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (svq *ServiceVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := svq.querySpec()
	_spec.Node.Columns = svq.ctx.Fields
	if len(svq.ctx.Fields) > 0 {
		_spec.Unique = svq.ctx.Unique != nil && *svq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, svq.driver, _spec)
}

func (svq *ServiceVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(serviceversion.Table, serviceversion.Columns, sqlgraph.NewFieldSpec(serviceversion.FieldID, field.TypeInt))
	_spec.From = svq.sql
	if unique := svq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if svq.path != nil {
		_spec.Unique = true
	}
	if fields := svq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serviceversion.FieldID)
		for i := range fields {
			if fields[i] != serviceversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if svq.withService != nil {
			_spec.Node.AddColumnOnce(serviceversion.FieldServiceID)
		}
	}
	if ps := svq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := svq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := svq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := svq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (svq *ServiceVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(svq.driver.Dialect())
	t1 := builder.Table(serviceversion.Table)
	columns := svq.ctx.Fields
	if len(columns) == 0 {
		columns = serviceversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if svq.sql != nil {
		selector = svq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if svq.ctx.Unique != nil && *svq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range svq.predicates {
		p(selector)
	}
	for _, p := range svq.order {
		p(selector)
	}
	if offset := svq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := svq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ServiceVersionGroupBy is the group-by builder for ServiceVersion entities.
type ServiceVersionGroupBy struct {
	selector
	build *ServiceVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (svgb *ServiceVersionGroupBy) Aggregate(fns ...AggregateFunc) *ServiceVersionGroupBy {
	svgb.fns = append(svgb.fns, fns...)
	return svgb
}

// Scan applies the selector query and scans the result into the given value.
func (svgb *ServiceVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, svgb.build.ctx, "GroupBy")
	if err := svgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ServiceVersionQuery, *ServiceVersionGroupBy](ctx, svgb.build, svgb, svgb.build.inters, v)
}

func (svgb *ServiceVersionGroupBy) sqlScan(ctx context.Context, root *ServiceVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(svgb.fns))
	for _, fn := range svgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*svgb.flds)+len(svgb.fns))
		for _, f := range *svgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*svgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := svgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ServiceVersionSelect is the builder for selecting fields of ServiceVersion entities.
type ServiceVersionSelect struct {
	*ServiceVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (svs *ServiceVersionSelect) Aggregate(fns ...AggregateFunc) *ServiceVersionSelect {
	svs.fns = append(svs.fns, fns...)
	return svs
}

// Scan applies the selector query and scans the result into the given value.
func (svs *ServiceVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, svs.ctx, "Select")
	if err := svs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ServiceVersionQuery, *ServiceVersionSelect](ctx, svs.ServiceVersionQuery, svs, svs.inters, v)
}

func (svs *ServiceVersionSelect) sqlScan(ctx context.Context, root *ServiceVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(svs.fns))
	for _, fn := range svs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*svs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := svs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
