// Code generated by ent, DO NOT EDIT.

package serviceversion

import (
	"services/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldEQ(FieldName, v))
}

// CreatedOn applies equality check predicate on the "created_on" field. It's identical to CreatedOnEQ.
func CreatedOn(v time.Time) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldEQ(FieldCreatedOn, v))
}

// ServiceID applies equality check predicate on the "service_id" field. It's identical to ServiceIDEQ.
func ServiceID(v int) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldEQ(FieldServiceID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldContainsFold(FieldName, v))
}

// CreatedOnEQ applies the EQ predicate on the "created_on" field.
func CreatedOnEQ(v time.Time) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldEQ(FieldCreatedOn, v))
}

// CreatedOnNEQ applies the NEQ predicate on the "created_on" field.
func CreatedOnNEQ(v time.Time) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldNEQ(FieldCreatedOn, v))
}

// CreatedOnIn applies the In predicate on the "created_on" field.
func CreatedOnIn(vs ...time.Time) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldIn(FieldCreatedOn, vs...))
}

// CreatedOnNotIn applies the NotIn predicate on the "created_on" field.
func CreatedOnNotIn(vs ...time.Time) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldNotIn(FieldCreatedOn, vs...))
}

// CreatedOnGT applies the GT predicate on the "created_on" field.
func CreatedOnGT(v time.Time) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldGT(FieldCreatedOn, v))
}

// CreatedOnGTE applies the GTE predicate on the "created_on" field.
func CreatedOnGTE(v time.Time) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldGTE(FieldCreatedOn, v))
}

// CreatedOnLT applies the LT predicate on the "created_on" field.
func CreatedOnLT(v time.Time) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldLT(FieldCreatedOn, v))
}

// CreatedOnLTE applies the LTE predicate on the "created_on" field.
func CreatedOnLTE(v time.Time) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldLTE(FieldCreatedOn, v))
}

// ServiceIDEQ applies the EQ predicate on the "service_id" field.
func ServiceIDEQ(v int) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldEQ(FieldServiceID, v))
}

// ServiceIDNEQ applies the NEQ predicate on the "service_id" field.
func ServiceIDNEQ(v int) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldNEQ(FieldServiceID, v))
}

// ServiceIDIn applies the In predicate on the "service_id" field.
func ServiceIDIn(vs ...int) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldIn(FieldServiceID, vs...))
}

// ServiceIDNotIn applies the NotIn predicate on the "service_id" field.
func ServiceIDNotIn(vs ...int) predicate.ServiceVersion {
	return predicate.ServiceVersion(sql.FieldNotIn(FieldServiceID, vs...))
}

// HasService applies the HasEdge predicate on the "service" edge.
func HasService() predicate.ServiceVersion {
	return predicate.ServiceVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ServiceTable, ServiceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServiceWith applies the HasEdge predicate on the "service" edge with a given conditions (other predicates).
func HasServiceWith(preds ...predicate.Service) predicate.ServiceVersion {
	return predicate.ServiceVersion(func(s *sql.Selector) {
		step := newServiceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ServiceVersion) predicate.ServiceVersion {
	return predicate.ServiceVersion(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ServiceVersion) predicate.ServiceVersion {
	return predicate.ServiceVersion(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ServiceVersion) predicate.ServiceVersion {
	return predicate.ServiceVersion(func(s *sql.Selector) {
		p(s.Not())
	})
}
