// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Service is the predicate function for service builders.
type Service func(*sql.Selector)

// ServiceVersion is the predicate function for serviceversion builders.
type ServiceVersion func(*sql.Selector)
